### PR TITLE
Drop travis which is outdated and not relevant

### PR DESCRIPTION
**Pull request by soltysh**
/assign @mfojtik

### CODE REVIEW

**Comment by stlaz** [comment]
/hold
the travis build seem to have failed on https://github.com/openshift/client-go/pull/169 where the author claims `make generate` does not do anything for them on the current master, but passed on https://github.com/openshift/client-go/pull/167 where `make generate` did perform changes (after fixing the script a bit to keep it from failing, most probably because I can't use the script correctly).

**Comment by soltysh** [comment]
/hold cancel
we never blocked on travis failure, our CI is sufficient in performing the necessary checks.

**Comment by stlaz** [comment]
Agree. The CI verify job and Travis do not appear to be 1-1 identical, though, the CI job will ignore build failures: https://github.com/openshift/release/blob/master/ci-operator/config/openshift/client-go/openshift-client-go-master.yaml#L19

**Comment by soltysh** [comment]
> Agree. The CI verify job and Travis do not appear to be 1-1 identical though, the CI job will ignore build failures: https://github.com/openshift/release/blob/master/ci-operator/config/openshift/client-go/openshift-client-go-master.yaml#L19

Good catch, fixed in https://github.com/openshift/release/pull/13811

**Pull request merged**
