### PR TITLE
Update deps to pick up containerRuntimeSearchRegitries

### PR DESCRIPTION
**Pull request by umohnani8**
Added a new field called containerRuntimeSearchRegistries
under RegistrySources in the Image CR struct. Vendor in
the api changes to pick up the new dependency.

openshift/api PR: https://github.com/openshift/api/pull/628

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@bparees @soltysh PTAL

**Comment by umohnani8** [comment]
Looks like `hack/verify-codegen.sh` is failing, but when I ran `make generate` locally, nothing new was generated. Any idea what I am doing wrong? I am on go 1.13 as that is the version being used here.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by umohnani8** [comment]
@soltysh what can I do to get past the travis failure? `make generate` doesn't generate anything new for me.

**Comment by stlaz** [comment]
/hold
this works fine for me in https://github.com/openshift/client-go/pull/167, and `make generate` actually did perform some changes. Make sure it did not fail for you.

**Comment by umohnani8** [comment]
@stlaz I am not seeing any failures after running `make generate` and there are no changes as well. These are the steps I followed:
```
go get github.come/openhift/api@mycommit
go mod tidy
go mod vendor
go mode verify
make generate
```
Did I miss a step somewhere?

**Comment by soltysh** [comment]
@umohnani8 I'd suggest trying with go1.15 which is what we use

**Comment by umohnani8** [comment]
go 1.15 worked for me, but looks like https://github.com/openshift/client-go/pull/167 pulled in the api changes I wanted. closing now.

**Pull request closed without merging**
