### PR TITLE
Update to account for OperatorHub config API

### PR DESCRIPTION
**Pull request by aravindhp**
operatorhubs.config.openshift.io was added in https://github.com/openshift/api/pull/388. This PR updates client-go to account for that addition by running:

`make update-deps`
`make generate`

### CODE REVIEW

**Comment by mrogers950** [comment]
@shawn-hurley @aravindhp looks OK to me wrt auth API changes pulled in.

**Comment by damemi** [comment]
/lgtm
all the other changes are comments and 1 added field

**Comment by aravindhp** [comment]
@patrickdillon please review the proxy changes that were pulled in.

**Comment by danehans** [comment]
PR includes the necessary updates to proxy type.

/lgtm

**Comment by jwforres** [comment]
manually approved as all normal approvers are out of office, all relevant teams had ack'ed

**Pull request merged**
