### PR TITLE
Update api to include Registry

### PR DESCRIPTION
**Pull request by mrunalp**
@bparees @adambkaplan ptal

I am not certain that I followed the steps correctly. I changed the glide.lock version of openshift/api to the commit that merged @umohnani8 PR and than ran glide install. I created the bump PR from that (it didn't update the timestamp in glide.lock though).

Then I ran ./hack/update-codegen.sh to generate code for the second commit.

Does that sound right?

cc: @umohnani8

### CODE REVIEW

**Comment by bparees** [comment]
@mrunalp you should have just run "make update-deps" and committed those changes as "bump(*)", then run "make generate" and commit those changes as "generated".

you shouldn't manually touch glide.lock.

**Comment by bparees** [comment]
(it looks like you got what i would have expected, but it would be best to go back and re-do the bump properly)

**Comment by mrunalp** [comment]
@bparees Thanks! done and pushed.

**Comment by mrunalp** [comment]
@smarterclayton for approval

**Comment by bparees** [comment]
@derekwaynecarr approved the api change, presumably he can approve the client-go bump too.

**Pull request merged**
