### PR TITLE
Add codegen verification script

### PR DESCRIPTION
**Pull request by soltysh**
@deads2k I was trying to figure out a way to write the verification script for client-go earlier today but I have so many doubts, I'll reach out to you and we need to discuss this more in-depth. For now this is adding a verification for the codegen, at least.

### CODE REVIEW

**Comment by deads2k** [comment]
travis says something broke.

/assign sttts

**Comment by soltysh** [comment]
> travis says something broke.

Lemme check, it didn't kick off right after I've added it, for some unknown reason.

**Comment by soltysh** [comment]
My bad, typo in `.PHONY` target, missing `:`. Updated should be good to go.

**Comment by soltysh** [comment]
[(3) Add verify script for client-go and api](https://trello.com/c/AFDpNB5h/1098-3-add-verify-script-for-client-go-and-api)

**Pull request merged**
