### PR TITLE
Bump k8s to 1.23.0

### PR DESCRIPTION
**Pull request by damemi**
Part of https://github.com/openshift/kubernetes/pull/1076

I hit the following errors trying to run `hack/update-codegen.sh`:

**In a container:**
```
$ docker run -it --rm -v $(pwd):/go/src/github.com/openshift/client-go/.:Z registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.17-openshift-4.10 sh

sh-4.4# hack/update-codegen.sh 
+ mv ./vendor/k8s.io/code-generator/generate-groups.sh ./vendor/k8s.io/code-generator/generate-groups.sh.orig
+ sed 's/ go install/#go install/g' ./vendor/k8s.io/code-generator/generate-groups.sh.orig
+ trap cleanup EXIT
+ go install ././vendor/k8s.io/code-generator/cmd/defaulter-gen ././vendor/k8s.io/code-generator/cmd/client-gen ././vendor/k8s.io/code-generator/cmd/lister-gen ././vendor/k8s.io/code-generator/cmd/informer-gen ././vendor/k8s.io/code-generator/cmd/deepcopy-gen
+ for group in apiserver apps authorization build cloudnetwork config image imageregistry network oauth project quota route samples security securityinternal template user
+ bash ./vendor/k8s.io/code-generator/generate-groups.sh client,lister,informer github.com/openshift/client-go/apiserver github.com/openshift/api apiserver:v1 --go-header-file hack/../hack/boilerplate.txt --plural-exceptions=DNS:DNSes,DNSList:DNSList,Endpoints:Endpoints,Features:Features,FeaturesList:FeaturesList,SecurityContextConstraints:SecurityContextConstraints
install: target 'k8s.io/code-generator/cmd/deepcopy-gen' is not a directory
+ cleanup
+ mv ./vendor/k8s.io/code-generator/generate-groups.sh.orig ./vendor/k8s.io/code-generator/generate-groups.sh
```

**Locally:**
```
$ hack/update-codegen.sh 
+ mv ./vendor/k8s.io/code-generator/generate-groups.sh ./vendor/k8s.io/code-generator/generate-groups.sh.orig
+ sed 's/ go install/#go install/g' ./vendor/k8s.io/code-generator/generate-groups.sh.orig
+ trap cleanup EXIT
+ go install ././vendor/k8s.io/code-generator/cmd/defaulter-gen ././vendor/k8s.io/code-generator/cmd/client-gen ././vendor/k8s.io/code-generator/cmd/lister-gen ././vendor/k8s.io/code-generator/cmd/informer-gen ././vendor/k8s.io/code-generator/cmd/deepcopy-gen
+ for group in apiserver apps authorization build cloudnetwork config image imageregistry network oauth project quota route samples security securityinternal template user
+ bash ./vendor/k8s.io/code-generator/generate-groups.sh client,lister,informer github.com/openshift/client-go/apiserver github.com/openshift/api apiserver:v1 --go-header-file hack/../hack/boilerplate.txt --plural-exceptions=DNS:DNSes,DNSList:DNSList,Endpoints:Endpoints,Features:Features,FeaturesList:FeaturesList,SecurityContextConstraints:SecurityContextConstraints
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
+ cleanup
+ mv ./vendor/k8s.io/code-generator/generate-groups.sh.orig ./vendor/k8s.io/code-generator/generate-groups.sh
```

### CODE REVIEW

**Comment by damemi** [comment]
CI failures look the same as what I saw locally in the PR description. @soltysh any idea about these? https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_client-go/203/pull-ci-openshift-client-go-master-verify/1466459661250072576

**Review by damemi — COMMENTED** [review]
/hold
for https://github.com/openshift/api/pull/1076

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
