### PR TITLE
bump(*): update openshift/api

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by bparees** [comment]
travis isn't happy w/ this change:

```
+bash ./vendor/k8s.io/code-generator/generate-groups.sh client,lister,informer github.com/openshift/client-go/imageregistry github.com/openshift/api imageregistry:v1 --go-header-file hack/../hack/../hack/boilerplate.txt --plural-exceptions=DNS:DNSes,DNSList:DNSList,Endpoints:Endpoints,Features:Features,FeaturesList:FeaturesList,SecurityContextConstraints:SecurityContextConstraints --verify-only

Generating clientset for imageregistry:v1 at github.com/openshift/client-go/imageregistry/clientset

F0106 21:12:56.673055    4284 main.go:64] Error: Failed executing generator: some packages had errors:

errors in package "github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1":

output for "v1/imageregistry_client.go" differs; first existing/expected diff: 

  "\tImagePrunersGetter\n}\n\n// ImageregistryV1Client is used to interact with features provided by the im"

  "}\n\n// ImageregistryV1Client is used to interact with features provided by the imageregistry.operator"

output for "v1/generated_expansion.go" differs; first existing/expected diff: 

  "\ntype ImagePrunerExpansion interface{}\n"

  ""

errors in package "github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/fake":

output for "fake/fake_imageregistry_client.go" differs; first existing/expected diff: 

  "func (c *FakeImageregistryV1) ImagePruners() v1.ImagePrunerInterface {\n\treturn &FakeImagePruners{c}\n"

  "// RESTClient returns a RESTClient that is used to communicate\n// with API server by this client imp"

+cleanup

+mv ./vendor/k8s.io/code-generator/generate-groups.sh.orig ./vendor/k8s.io/code-generator/generate-groups.sh

Makefile:13: recipe for target 'verify' failed
```

**Comment by coreydaley** [comment]
@bparees ptal, fixed the error
I'm not sure why I always have to "git add -f vendor", I have searched and searched and can't find anything that would prevent git add from checking the vendor directory.

**Pull request merged**
