### PR TITLE
add generated code for config api

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k follow on to https://github.com/openshift/api/pull/111, ptal.

**Comment by deads2k** [comment]
yeah, this is it.  I didn't realize this one was still manual merges.

lgtm once the bump is real.

**Comment by bparees** [comment]
/hold cancel
@deads2k bump is real

**Comment by bparees** [comment]
@deads2k probably needs your signoff on the bump(*) commit.

**Pull request merged**
