### PR TITLE
CONSOLE-2376: Dynamic plugins for Console

### PR DESCRIPTION
**Pull request by jhadvig**
Generating client/informer/listener for ConsolePlugins CRD
Vendoring https://github.com/openshift/api/pull/764

/hold for approvals
/assign @ahardin-rh @yapei @sferich888 @reestr

### CODE REVIEW

**Comment by yapei** [comment]
Looks good from QE's point of view

**Comment by jhadvig** [comment]
Updated the PR by removing the my vendored api changed.

@soltysh PTAL

cc'ing @spadgett

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
Manually adding valid-bug label per https://github.com/openshift/api/pull/764#issuecomment-758693484

**Pull request merged**
